// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAction.proto

package com.wxm.user;

public interface UserActionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserActionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user = 1;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string itemSetId = 2;</code>
   */
  java.lang.String getItemSetId();
  /**
   * <code>string itemSetId = 2;</code>
   */
  com.google.protobuf.ByteString
      getItemSetIdBytes();

  /**
   * <code>string itemId = 3;</code>
   */
  java.lang.String getItemId();
  /**
   * <code>string itemId = 3;</code>
   */
  com.google.protobuf.ByteString
      getItemIdBytes();

  /**
   * <code>int32 action = 4;</code>
   */
  int getAction();
}
