// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAction.proto

package com.wxm.user;

public interface UserActionsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserActionsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user = 1;</code>
   */
  java.lang.String getUser();
  /**
   * <code>string user = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserBytes();

  /**
   * <code>string itemSetId = 2;</code>
   */
  java.lang.String getItemSetId();
  /**
   * <code>string itemSetId = 2;</code>
   */
  com.google.protobuf.ByteString
      getItemSetIdBytes();

  /**
   * <code>string itemIds = 3;</code>
   */
  java.lang.String getItemIds();
  /**
   * <code>string itemIds = 3;</code>
   */
  com.google.protobuf.ByteString
      getItemIdsBytes();

  /**
   * <code>int32 action = 4;</code>
   */
  int getAction();
}
