// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAction.proto

package com.wxm.user;

public interface UserActionReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserActionReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
