// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userAction.proto

package com.wxm.user;

public final class UserActionProto {
  private UserActionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserActionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserActionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserActionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserActionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserActionReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserActionReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020userAction.proto\"T\n\021UserActionRequest\022" +
      "\014\n\004user\030\001 \001(\t\022\021\n\titemSetId\030\002 \001(\t\022\016\n\006item" +
      "Id\030\003 \001(\t\022\016\n\006action\030\004 \001(\005\"V\n\022UserActionsR" +
      "equest\022\014\n\004user\030\001 \001(\t\022\021\n\titemSetId\030\002 \001(\t\022" +
      "\017\n\007itemIds\030\003 \001(\t\022\016\n\006action\030\004 \001(\005\"\"\n\017User" +
      "ActionReply\022\017\n\007message\030\001 \001(\t2\274\001\n\nUserAct" +
      "ion\0228\n\016saveUserAction\022\022.UserActionReques" +
      "t\032\020.UserActionReply\"\000\022:\n\017saveUserActions" +
      "\022\023.UserActionsRequest\032\020.UserActionReply\"" +
      "\000\0228\n\rgetUserAction\022\023.UserActionsRequest\032" +
      "\020.UserActionReply\"\000B!\n\014com.wxm.userB\017Use" +
      "rActionProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UserActionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserActionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserActionRequest_descriptor,
        new java.lang.String[] { "User", "ItemSetId", "ItemId", "Action", });
    internal_static_UserActionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UserActionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserActionsRequest_descriptor,
        new java.lang.String[] { "User", "ItemSetId", "ItemIds", "Action", });
    internal_static_UserActionReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_UserActionReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserActionReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
